on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
name: 🚀 Deploy website on push
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: 📂 Sync files
      with:
        ftp_host: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "static"
        dist_target_dir: "public_html/devop/test"
        delete: "false"
        exclude: "'^logs/' '^README.md'"
